require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Lejr' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNBugfender', :path => '../node_modules/@bugfender/rn-bugfender'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'LejrTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Lejr-tvOS' do
  # Pods for Lejr-tvOS

  target 'Lejr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end